// The wire protocol between the TrustedCourier core and a Backend Plugin.
// Plugin Authors do not use it directly: the plugin SDK's Serve hides it.
//
// Regenerate with `buf generate` in this directory.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: backend.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{0}
}

// CapabilitiesResponse is the plugin's first answer after the go-plugin
// handshake, so it also carries the process properties the core checks
// before it trusts the plugin with Secrets.
type CapabilitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CourierKeyWrite bool                   `protobuf:"varint,1,opt,name=courier_key_write,json=courierKeyWrite,proto3" json:"courier_key_write,omitempty"`
	// fips140_enabled reports whether the plugin process runs in FIPS 140-3
	// mode. The core refuses a plugin that does not when it is in FIPS mode
	// itself.
	Fips140Enabled bool `protobuf:"varint,2,opt,name=fips140_enabled,json=fips140Enabled,proto3" json:"fips140_enabled,omitempty"`
	// fips140_version is the Go FIPS 140-3 module version the plugin was built
	// with ("latest" for an unvalidated in-tree module).
	Fips140Version string `protobuf:"bytes,3,opt,name=fips140_version,json=fips140Version,proto3" json:"fips140_version,omitempty"`
	// fips140_only reports whether the plugin process runs in FIPS 140-3
	// "only" mode, where a non-approved algorithm panics rather than falls
	// back. A core in only mode refuses a plugin that is not.
	Fips140Only   bool `protobuf:"varint,4,opt,name=fips140_only,json=fips140Only,proto3" json:"fips140_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitiesResponse) GetCourierKeyWrite() bool {
	if x != nil {
		return x.CourierKeyWrite
	}
	return false
}

func (x *CapabilitiesResponse) GetFips140Enabled() bool {
	if x != nil {
		return x.Fips140Enabled
	}
	return false
}

func (x *CapabilitiesResponse) GetFips140Version() string {
	if x != nil {
		return x.Fips140Version
	}
	return ""
}

func (x *CapabilitiesResponse) GetFips140Only() bool {
	if x != nil {
		return x.Fips140Only
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{6}
}

func (x *ListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []string               `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{7}
}

func (x *ListResponse) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

type WriteCourierKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCourierKeyRequest) Reset() {
	*x = WriteCourierKeyRequest{}
	mi := &file_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCourierKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCourierKeyRequest) ProtoMessage() {}

func (x *WriteCourierKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCourierKeyRequest.ProtoReflect.Descriptor instead.
func (*WriteCourierKeyRequest) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{8}
}

func (x *WriteCourierKeyRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *WriteCourierKeyRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type WriteCourierKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCourierKeyResponse) Reset() {
	*x = WriteCourierKeyResponse{}
	mi := &file_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCourierKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCourierKeyResponse) ProtoMessage() {}

func (x *WriteCourierKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCourierKeyResponse.ProtoReflect.Descriptor instead.
func (*WriteCourierKeyResponse) Descriptor() ([]byte, []int) {
	return file_backend_proto_rawDescGZIP(), []int{9}
}

var File_backend_proto protoreflect.FileDescriptor

const file_backend_proto_rawDesc = "" +
	"\n" +
	"\rbackend.proto\x12\x19trustedcourier.backend.v1\"\x15\n" +
	"\x13CapabilitiesRequest\"\xb7\x01\n" +
	"\x14CapabilitiesResponse\x12*\n" +
	"\x11courier_key_write\x18\x01 \x01(\bR\x0fcourierKeyWrite\x12'\n" +
	"\x0ffips140_enabled\x18\x02 \x01(\bR\x0efips140Enabled\x12'\n" +
	"\x0ffips140_version\x18\x03 \x01(\tR\x0efips140Version\x12!\n" +
	"\ffips140_only\x18\x04 \x01(\bR\vfips140Only\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"(\n" +
	"\n" +
	"GetRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"#\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"%\n" +
	"\vListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\",\n" +
	"\fListResponse\x12\x1c\n" +
	"\tlocations\x18\x01 \x03(\tR\tlocations\"J\n" +
	"\x16WriteCourierKeyRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x19\n" +
	"\x17WriteCourierKeyResponse2\x82\x04\n" +
	"\aBackend\x12o\n" +
	"\fCapabilities\x12..trustedcourier.backend.v1.CapabilitiesRequest\x1a/.trustedcourier.backend.v1.CapabilitiesResponse\x12]\n" +
	"\x06Health\x12(.trustedcourier.backend.v1.HealthRequest\x1a).trustedcourier.backend.v1.HealthResponse\x12T\n" +
	"\x03Get\x12%.trustedcourier.backend.v1.GetRequest\x1a&.trustedcourier.backend.v1.GetResponse\x12W\n" +
	"\x04List\x12&.trustedcourier.backend.v1.ListRequest\x1a'.trustedcourier.backend.v1.ListResponse\x12x\n" +
	"\x0fWriteCourierKey\x121.trustedcourier.backend.v1.WriteCourierKeyRequest\x1a2.trustedcourier.backend.v1.WriteCourierKeyResponseB8Z6github.com/potto007/TrustedCourier/sdk/plugin/protocolb\x06proto3"

var (
	file_backend_proto_rawDescOnce sync.Once
	file_backend_proto_rawDescData []byte
)

func file_backend_proto_rawDescGZIP() []byte {
	file_backend_proto_rawDescOnce.Do(func() {
		file_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)))
	})
	return file_backend_proto_rawDescData
}

var file_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_backend_proto_goTypes = []any{
	(*CapabilitiesRequest)(nil),     // 0: trustedcourier.backend.v1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),    // 1: trustedcourier.backend.v1.CapabilitiesResponse
	(*HealthRequest)(nil),           // 2: trustedcourier.backend.v1.HealthRequest
	(*HealthResponse)(nil),          // 3: trustedcourier.backend.v1.HealthResponse
	(*GetRequest)(nil),              // 4: trustedcourier.backend.v1.GetRequest
	(*GetResponse)(nil),             // 5: trustedcourier.backend.v1.GetResponse
	(*ListRequest)(nil),             // 6: trustedcourier.backend.v1.ListRequest
	(*ListResponse)(nil),            // 7: trustedcourier.backend.v1.ListResponse
	(*WriteCourierKeyRequest)(nil),  // 8: trustedcourier.backend.v1.WriteCourierKeyRequest
	(*WriteCourierKeyResponse)(nil), // 9: trustedcourier.backend.v1.WriteCourierKeyResponse
}
var file_backend_proto_depIdxs = []int32{
	0, // 0: trustedcourier.backend.v1.Backend.Capabilities:input_type -> trustedcourier.backend.v1.CapabilitiesRequest
	2, // 1: trustedcourier.backend.v1.Backend.Health:input_type -> trustedcourier.backend.v1.HealthRequest
	4, // 2: trustedcourier.backend.v1.Backend.Get:input_type -> trustedcourier.backend.v1.GetRequest
	6, // 3: trustedcourier.backend.v1.Backend.List:input_type -> trustedcourier.backend.v1.ListRequest
	8, // 4: trustedcourier.backend.v1.Backend.WriteCourierKey:input_type -> trustedcourier.backend.v1.WriteCourierKeyRequest
	1, // 5: trustedcourier.backend.v1.Backend.Capabilities:output_type -> trustedcourier.backend.v1.CapabilitiesResponse
	3, // 6: trustedcourier.backend.v1.Backend.Health:output_type -> trustedcourier.backend.v1.HealthResponse
	5, // 7: trustedcourier.backend.v1.Backend.Get:output_type -> trustedcourier.backend.v1.GetResponse
	7, // 8: trustedcourier.backend.v1.Backend.List:output_type -> trustedcourier.backend.v1.ListResponse
	9, // 9: trustedcourier.backend.v1.Backend.WriteCourierKey:output_type -> trustedcourier.backend.v1.WriteCourierKeyResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backend_proto_init() }
func file_backend_proto_init() {
	if File_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_proto_rawDesc), len(file_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_proto_goTypes,
		DependencyIndexes: file_backend_proto_depIdxs,
		MessageInfos:      file_backend_proto_msgTypes,
	}.Build()
	File_backend_proto = out.File
	file_backend_proto_goTypes = nil
	file_backend_proto_depIdxs = nil
}
